services:
  nats:
    image: nats:2-alpine
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data

  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs-data:/data
    environment:
      RUSTFS_ROOT_USER: "boreadmin"
      RUSTFS_ROOT_PASSWORD: "boreadmin"
      RUSTFS_ACCESS_KEY: "rustfsadmin"
      RUSTFS_SECRET_KEY: "rustfsadmin"

volumes:
  nats-data:
  rustfs-data:
